from enum import Enum


class Response(Enum):
    LOGIN_SUCCESS = 0
    USER_FOUND = 1
    USER_NOT_FOUND = 2
    INCORRECT_PASSWORD = 3
    USER_ADDED = 4
    USER_NOT_ADDED = 5
    PORTFOLIO_ADDED = 6
    PORTFOLIO_NOT_ADDED = 7
    PORTFOLIO_UPDATED = 8
    PORTFOLIO_NOT_UPDATED = 9
    PORTFOLIO_DELETED = 10
    PORTFOLIO_NOT_DELETED = 11
    STOCK_ADDED = 12
    STOCK_NOT_ADDED = 13
    STOCK_UPDATED = 14
    STOCK_NOT_UPDATED = 15
    STOCK_DELETED = 16
    STOCK_NOT_DELETED = 17
